# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 200)
        Form.setMinimumSize(QtCore.QSize(300, 200))
        Form.setMaximumSize(QtCore.QSize(300, 200))
        Form.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.submitButton = QtWidgets.QPushButton(Form)
        self.submitButton.setObjectName("submitButton")
        self.gridLayout.addWidget(self.submitButton, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.propertyLabel = QtWidgets.QLabel(Form)
        self.propertyLabel.setObjectName("propertyLabel")
        self.horizontalLayout.addWidget(self.propertyLabel)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setMinimum(-100)
        self.spinBox.setMaximum(100)
        self.spinBox.setSingleStep(1)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.slider = QtWidgets.QSlider(Form)
        self.slider.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.slider.setFont(font)
        self.slider.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.slider.setAcceptDrops(False)
        self.slider.setMinimum(-100)
        self.slider.setMaximum(100)
        self.slider.setSingleStep(1)
        self.slider.setPageStep(1)
        self.slider.setTracking(True)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setInvertedAppearance(False)
        self.slider.setInvertedControls(False)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.submitButton.setText(_translate("Form", "确定"))
        self.propertyLabel.setText(_translate("Form", "亮度"))
